server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  servlet:
  #设置项目context path
    context-path: /his
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost/his?characterEncoding=utf8
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #Spring Data JPA
    jpa:
      database: MYSQL
      # 显示后台处理的SQL语句
      show-sql: true
       # 自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表
      hibernate:
        ddl-auto: update
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.neuedu.his.pojo

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
